[package]
name = "ptrace"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.180"
nix = { version = "0.31.1", features = ["ptrace", "process", "user", "fs", "signal"] }
syscalls = "0.6.18"
